version: 0.0
os: linux
files:
  - source: index.js
    destination: /var/www/

permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300
      runas: ec2-user
